/* Curriculum data — single source of truth for nav, search, pager, progress.
   Reference playlist: "CKA Certification Course 2025" by Cloud With VarJosh
   https://www.youtube.com/playlist?list=PLmPit9IIdzwRjqD-l_sZBDdPlcSfKqpAt */
window.CURRICULUM = {
  playlist: "https://www.youtube.com/playlist?list=PLmPit9IIdzwRjqD-l_sZBDdPlcSfKqpAt",
  channel: "Cloud With VarJosh",
  modules: [
    { id:"m0", num:0, title:"Start Here", color:"#64748b",
      blurb:"What the course covers, how to study, and how this site is organised.",
      lessons:[
        { id:"d00", day:0, slug:"d00-roadmap", title:"Course Roadmap & How to Use This Site", yt:"vzOcHoNcwMg", mins:6,
          tags:["roadmap","cka","exam","syllabus","study plan"] },
      ]},
    { id:"m1", num:1, title:"Containers & Docker", color:"#0ea5e9",
      blurb:"Before Kubernetes: what a container really is, how images are built, and the Linux features underneath.",
      lessons:[
        { id:"d01", day:1, slug:"d01-docker-fundamentals", title:"Docker Fundamentals for Kubernetes", yt:"r3QWVLeA5qM", mins:14,
          tags:["docker","container","vm","image","namespaces","cgroups","overlayfs","runtime"] },
        { id:"d02", day:2, slug:"d02-first-dockerfile", title:"Your First Dockerfile & Pushing to Docker Hub", yt:"YVq-3UWt63U", mins:12,
          tags:["dockerfile","build","push","docker hub","registry","tag","layers"] },
        { id:"d03", day:3, slug:"d03-docker-flags-ports", title:"Docker Flags, Dockerfile Deep Dive & Exposing Containers", yt:"MQ8fYqZwiQs", mins:13,
          tags:["docker run","-p","expose","port","env","detach","bridge","iptables","veth"] },
        { id:"d04", day:4, slug:"d04-cmd-vs-entrypoint", title:"CMD vs ENTRYPOINT & Essential Docker Commands", yt:"34l1gRszQS4", mins:12,
          tags:["cmd","entrypoint","exec form","shell form","pid 1","signals","docker exec","logs"] },
        { id:"d05", day:5, slug:"d05-multistage-builds", title:"Multi-Stage Builds & Image Optimization", yt:"8q3pJfE6Z_E", mins:11,
          tags:["multi-stage","distroless","alpine","image size","layers","cache","dockerignore"] },
      ]},
    { id:"m2", num:2, title:"Kubernetes Core", color:"#2f6fe4",
      blurb:"Why Kubernetes exists, the control plane and worker nodes, your first cluster, YAML, and Deployments.",
      lessons:[
        { id:"d06", day:6, slug:"d06-why-kubernetes", title:"Hello Kubernetes! Why & What Is Kubernetes?", yt:"2xNR2I0Jk-I", mins:12,
          tags:["why kubernetes","orchestration","scaling","self-healing","desired state","borg","cncf"] },
        { id:"d07", day:7, slug:"d07-architecture", title:"Kubernetes Architecture & Deployment Creation Workflow", yt:"-9Cslu8PTjU", mins:18,
          tags:["architecture","control plane","api server","etcd","scheduler","controller manager","kubelet","kube-proxy","container runtime","containerd"] },
        { id:"d08", day:8, slug:"d08-kind-cluster", title:"Setting Up a KIND Cluster & Kubernetes Context", yt:"wBF3YCMgZ7U", mins:12,
          tags:["kind","kubectl","install","kubeconfig","context","cluster","local"] },
        { id:"d09", day:9, slug:"d09-yaml-imperative-declarative", title:"YAML for Kubernetes · Imperative vs Declarative", yt:"LT3U9fkOVDQ", mins:14,
          tags:["yaml","manifest","apiVersion","kind","metadata","spec","imperative","declarative","apply","create","dry-run"] },
        { id:"d10", day:10, slug:"d10-replicasets-deployments", title:"ReplicationController, ReplicaSets & Deployments In Depth", yt:"_YNBhQGMut4", mins:18,
          tags:["replicaset","deployment","rolling update","rollout","rollback","revision","strategy","maxSurge","maxUnavailable","replicationcontroller"] },
      ]},
    { id:"m3", num:3, title:"Services, Networking Basics & Namespaces", color:"#0891b2",
      blurb:"How traffic reaches Pods: Services of every type, the imperative toolbox, and isolating work with Namespaces.",
      lessons:[
        { id:"d11", day:11, slug:"d11-microservices-3tier", title:"Microservices & 3-Tier Architecture for Kubernetes", yt:"waJ8brXMtYg", mins:11,
          tags:["microservices","monolith","3-tier","frontend","backend","database","design"] },
        { id:"d12", day:12, slug:"d12-services", title:"Services In Depth: ClusterIP, NodePort, LoadBalancer, ExternalName", yt:"92NB8oQBtnc", mins:20,
          tags:["service","clusterip","nodeport","loadbalancer","externalname","headless","endpoints","endpointslice","kube-proxy","iptables","selector"] },
        { id:"d13", day:13, slug:"d13-imperative-commands", title:"Imperative Commands for Deployments, Services & Troubleshooting", yt:"ZDFqVFbX0Ic", mins:12,
          tags:["kubectl run","kubectl create","kubectl expose","kubectl set image","scale","edit","dry-run","describe","logs","exec"] },
        { id:"d14", day:14, slug:"d14-namespaces", title:"Namespaces: Isolation & Resource Management", yt:"uDlhbtGy1AU", mins:12,
          tags:["namespace","resourcequota","limitrange","kube-system","default","dns","fqdn","cluster.local"] },
      ]},
    { id:"m4", num:4, title:"Scheduling & Resources", color:"#7c3aed",
      blurb:"How the scheduler picks a node, how to steer it, and how CPU/memory requests, limits and autoscaling work.",
      lessons:[
        { id:"d15", day:15, slug:"d15-manual-scheduling-static-pods", title:"Manual Scheduling & Static Pods", yt:"moZNbHD5Lxg", mins:12,
          tags:["nodeName","static pod","manifests","kubelet","scheduler","binding","mirror pod"] },
        { id:"d16", day:16, slug:"d16-taints-tolerations", title:"Taints & Tolerations", yt:"G_Ro0urceF0", mins:13,
          tags:["taint","toleration","NoSchedule","PreferNoSchedule","NoExecute","tolerationSeconds","control-plane taint"] },
        { id:"d17", day:17, slug:"d17-node-selector-affinity", title:"Node Selector & Node Affinity", yt:"vaW2pwSXdb4", mins:13,
          tags:["nodeSelector","nodeAffinity","labels","requiredDuringScheduling","preferredDuringScheduling","operators","In","Exists"] },
        { id:"d18", day:18, slug:"d18-taints-vs-affinity", title:"Taints & Tolerations vs Node Affinity — Mastering Pod Placement", yt:"itEINIqjNfE", mins:10,
          tags:["taints vs affinity","pod affinity","anti-affinity","topologyKey","scheduling","dedicated nodes"] },
        { id:"d19", day:19, slug:"d19-requests-limits", title:"Requests, Limits & LimitRange", yt:"Bu4RocrMx0g", mins:15,
          tags:["requests","limits","cpu","memory","millicores","OOMKilled","throttling","LimitRange","QoS","Guaranteed","Burstable","BestEffort","cgroups"] },
        { id:"d20", day:20, slug:"d20-autoscaling", title:"Autoscaling: HPA & VPA", yt:"hVLSjcJzE4U", mins:15,
          tags:["hpa","vpa","autoscaling","metrics-server","cluster autoscaler","karpenter","targetCPUUtilization","scale"] },
      ]},
    { id:"m5", num:5, title:"Pod Design & Lifecycle", color:"#16a34a",
      blurb:"Multi-container patterns, what happens when a Pod starts, restarts and dies, and health probes.",
      lessons:[
        { id:"d21", day:21, slug:"d21-multi-container-pods", title:"Multi-Container Pods: Init, Sidecar, Ambassador, Adapter", yt:"VEwP_wF67Tw", mins:14,
          tags:["init container","sidecar","ambassador","adapter","multi-container","shared volume","localhost","native sidecar"] },
        { id:"d22", day:22, slug:"d22-pod-lifecycle", title:"Pod Termination, Restart Policy, Image Pull Policy, Lifecycle & Errors", yt:"miZl-7QI3Pw", mins:16,
          tags:["pod phase","Pending","Running","Succeeded","Failed","CrashLoopBackOff","ImagePullBackOff","restartPolicy","imagePullPolicy","SIGTERM","grace period","preStop","postStart"] },
        { id:"d23", day:23, slug:"d23-health-probes", title:"Health Probes: Readiness vs Liveness vs Startup", yt:"ANSBnfil75Y", mins:14,
          tags:["liveness","readiness","startup","probe","httpGet","tcpSocket","exec","grpc","failureThreshold","initialDelaySeconds"] },
      ]},
    { id:"m6", num:6, title:"Storage", color:"#d97706",
      blurb:"From Docker volumes to Kubernetes ephemeral and persistent storage, plus the CNI/CSI/CRI plugin model.",
      lessons:[
        { id:"d24", day:24, slug:"d24-docker-volumes", title:"Docker Volumes: Foundation for Persistent Storage", yt:"5t3yHFoqK6g", mins:11,
          tags:["docker volume","bind mount","tmpfs","mount","persistence","-v","--mount"] },
        { id:"d25", day:25, slug:"d25-cni-csi-cri", title:"Kubernetes Core & Extensions: CNI, CSI, CRI, Add-ons & Plugins", yt:"AVovCH0dvyM", mins:12,
          tags:["cni","csi","cri","containerd","cri-o","calico","cilium","flannel","addons","plugins","interfaces"] },
        { id:"d26", day:26, slug:"d26-ephemeral-volumes", title:"Ephemeral Volumes: emptyDir & downwardAPI", yt:"Zyublb8bSbU", mins:11,
          tags:["emptyDir","downwardAPI","ephemeral","volumes","medium: Memory","sizeLimit","projected"] },
        { id:"d27", day:27, slug:"d27-persistent-volumes", title:"Persistent Storage: PV, PVC, StorageClass & hostPath", yt:"C6fqoSnbrck", mins:18,
          tags:["persistentvolume","pv","pvc","storageclass","hostPath","dynamic provisioning","reclaim policy","access modes","ReadWriteOnce","binding","volumeBindingMode"] },
      ]},
    { id:"m7", num:7, title:"Configuration & Workload Controllers", color:"#db2777",
      blurb:"Injecting config and secrets, and the controllers beyond Deployments: DaemonSets, Jobs and CronJobs.",
      lessons:[
        { id:"d28", day:28, slug:"d28-configmaps-secrets", title:"ConfigMaps & Secrets", yt:"9vch82LomtE", mins:16,
          tags:["configmap","secret","env","envFrom","volume","base64","immutable","stringData","encryption at rest","etcd"] },
        { id:"d29", day:29, slug:"d29-daemonset-job-cronjob", title:"DaemonSet, Job & CronJob", yt:"gKbIkyE0TTI", mins:15,
          tags:["daemonset","job","cronjob","completions","parallelism","backoffLimit","schedule","cron","concurrencyPolicy","ttlSecondsAfterFinished"] },
      ]},
    { id:"m8", num:8, title:"Security: TLS, Authentication & Authorization", color:"#dc2626",
      blurb:"Encryption from first principles, how every Kubernetes component trusts every other, and who is allowed to do what.",
      lessons:[
        { id:"d30", day:30, slug:"d30-https-ssh-encryption", title:"How HTTPS & SSH Work: Symmetric vs Asymmetric Encryption", yt:"MkGPyJqCkB4", mins:14,
          tags:["encryption","symmetric","asymmetric","public key","private key","https","ssh","hashing","signature"] },
        { id:"d31", day:31, slug:"d31-tls-part1", title:"TLS Masterclass 1: Mutual Auth, TLS 1.3 & Types of CAs", yt:"afQIvp5a0wM", mins:15,
          tags:["tls","handshake","certificate","ca","root ca","intermediate","tls 1.3","ssh keys","mutual auth"] },
        { id:"d32", day:32, slug:"d32-tls-part2-kubeconfig", title:"TLS Masterclass 2: mTLS, kubeconfig & Context", yt:"VBlI0IG4ReI", mins:14,
          tags:["mtls","kubeconfig","context","cluster","user","client certificate","certificate-authority-data","client-key-data"] },
        { id:"d33", day:33, slug:"d33-tls-part3-mtls", title:"TLS Masterclass 3: Root CAs, TLS Auth Flow & mTLS Inside the Cluster", yt:"rVFlVIs2gDU", mins:16,
          tags:["pki","/etc/kubernetes/pki","etcd ca","front-proxy","apiserver-kubelet-client","kubelet serving","certificate chain","x509"] },
        { id:"d34", day:34, slug:"d34-tls-part4-csr", title:"TLS Masterclass 4: CSRs & External User Access", yt:"RZ9O5JJeq9k", mins:14,
          tags:["csr","certificatesigningrequest","openssl","approve","kubectl certificate","user access","signerName","kube-apiserver-client"] },
        { id:"d35", day:35, slug:"d35-authorization-api", title:"Authorization Modes & the Kubernetes API", yt:"DkKc3RCW2BE", mins:14,
          tags:["authorization","abac","rbac","node authorizer","webhook","AlwaysAllow","api groups","resources","verbs","kubectl api-resources","kubectl proxy"] },
        { id:"d36", day:36, slug:"d36-rbac", title:"RBAC Authorization Explained", yt:"bP9oqYF_xlE", mins:16,
          tags:["rbac","role","rolebinding","clusterrole","clusterrolebinding","verbs","auth can-i","aggregation","subjects"] },
        { id:"d37", day:37, slug:"d37-service-accounts", title:"Service Accounts & Authentication", yt:"WsQT7y5C-qU", mins:14,
          tags:["serviceaccount","token","projected token","bound token","automountServiceAccountToken","authentication","oidc","users","groups"] },
        { id:"d38", day:38, slug:"d38-admission-controllers", title:"Admission Controllers: Mutating & Validating", yt:"iZTQv4F7Djk", mins:14,
          tags:["admission controller","mutating","validating","webhook","LimitRanger","NamespaceLifecycle","PodSecurity","ValidatingAdmissionPolicy","enable-admission-plugins"] },
      ]},
    { id:"m9", num:9, title:"Extending & Packaging Kubernetes", color:"#7c3aed",
      blurb:"Teach the API new resource types, automate with Operators, lock down Pods, and manage manifests with Kustomize and Helm.",
      lessons:[
        { id:"d39", day:39, slug:"d39-crds", title:"Custom Resources (CR) & Custom Resource Definitions (CRD)", yt:"y4e7nQzu_8E", mins:13,
          tags:["crd","custom resource","openapi schema","versions","scope","api extension","kubectl explain"] },
        { id:"d40", day:40, slug:"d40-operators", title:"Kubernetes Operators Deep Dive", yt:"hxgmG1qYU2M", mins:14,
          tags:["operator","controller","reconcile","control loop","olm","kubebuilder","operator sdk","prometheus operator"] },
        { id:"d41", day:41, slug:"d41-pod-security", title:"Pod Security: Security Context & Linux Capabilities", yt:"ZoTKkmY6VSw", mins:15,
          tags:["securityContext","runAsUser","runAsNonRoot","capabilities","privileged","readOnlyRootFilesystem","allowPrivilegeEscalation","seccomp","pod security admission","pod security standards"] },
        { id:"d42", day:42, slug:"d42-kustomize", title:"Kustomize Explained", yt:"AKr5tc4nN2w", mins:13,
          tags:["kustomize","kustomization","base","overlay","patches","strategic merge","json patch","configMapGenerator","kubectl -k"] },
        { id:"d43", day:43, slug:"d43-helm", title:"Helm Charts for Beginners", yt:"yvV_ZUottOM", mins:15,
          tags:["helm","chart","values.yaml","templates","release","repo","upgrade","rollback","helm install","go templates"] },
      ]},
    { id:"m10", num:10, title:"Advanced Workloads", color:"#0ea5e9",
      blurb:"Stateful applications with stable identity, private registries, and Pod priority when the cluster runs out of room.",
      lessons:[
        { id:"d44", day:44, slug:"d44-statefulsets", title:"StatefulSets (with a Multi-AZ EKS Demo)", yt:"ES48aMk4Gys", mins:16,
          tags:["statefulset","headless service","volumeClaimTemplates","ordinal","stable network identity","podManagementPolicy","partition","multi-az"] },
        { id:"d45", day:45, slug:"d45-image-pull-secrets", title:"Pulling Private Images: imagePullSecrets & ServiceAccount", yt:"5p-Qw1zxoWE", mins:9,
          tags:["imagePullSecrets","docker-registry secret","private registry","serviceaccount","ecr","dockerconfigjson"] },
        { id:"d46", day:46, slug:"d46-pod-priority", title:"Pod Priority, PriorityClass & Preemption", yt:"rjqILqIoq7g", mins:11,
          tags:["priorityclass","preemption","priority","globalDefault","preemptionPolicy","system-cluster-critical","eviction"] },
      ]},
    { id:"m11", num:11, title:"Networking Deep Dive", color:"#0891b2",
      blurb:"Network policies, DNS inside the cluster, Ingress on real cloud load balancers, and the Gateway API.",
      lessons:[
        { id:"d47", day:47, slug:"d47-network-policies", title:"Network Policies with a Real-World Demo", yt:"5TKKG-uKU4o", mins:14,
          tags:["networkpolicy","ingress","egress","podSelector","namespaceSelector","ipBlock","default deny","cni","calico","cilium"] },
        { id:"d48", day:48, slug:"d48-dns-coredns", title:"How DNS Works — and How It Works in Kubernetes (CoreDNS)", yt:"9TosJ-z9x6Y", mins:18, extraYt:"hXFciOpUuOY",
          tags:["dns","coredns","fqdn","resolv.conf","ndots","search domains","svc.cluster.local","kube-dns","Corefile","headless dns","pod dns"] },
        { id:"d49", day:49, slug:"d49-ingress-part1", title:"Ingress 1: What, Why & the Real-World Flow", yt:"yj-ZlKTYDUI", mins:12,
          tags:["ingress","ingress controller","ingressclass","nginx","alb","host","path","rules","backend"] },
        { id:"d50", day:50, slug:"d50-ingress-part2", title:"Ingress 2: Path-Based Routing on EKS with AWS ALB", yt:"4d0dkj6Vc70", mins:14,
          tags:["ingress","path based routing","aws load balancer controller","alb","eks","annotations","pathType","Prefix","Exact"] },
        { id:"d51", day:51, slug:"d51-ingress-part3", title:"Ingress 3: TLS & Subdomain Routing on EKS with AWS ALB", yt:"ABqaWXSIFXc", mins:13,
          tags:["ingress tls","subdomain","host based routing","acm","cert-manager","tls secret","route53","external-dns"] },
        { id:"d52", day:52, slug:"d52-gateway-api-part1", title:"Gateway API 1: GatewayClass, Gateway & Routes", yt:"mkohNT5PCe8", mins:13,
          tags:["gateway api","gatewayclass","gateway","httproute","listeners","parentRefs","role oriented","ingress vs gateway"] },
        { id:"d53", day:53, slug:"d53-gateway-api-part2", title:"Gateway API 2: NGINX Gateway Fabric Demo", yt:"ojjeXUKRRjM", mins:12,
          tags:["nginx gateway fabric","httproute","matches","filters","backendRefs","traffic splitting","header routing"] },
      ]},
    { id:"m12", num:12, title:"Cluster Operations & Troubleshooting", color:"#dc2626",
      blurb:"Build and upgrade real clusters with kubeadm, observe them, fix broken control planes and nodes, and query anything with JSONPath.",
      lessons:[
        { id:"d54", day:54, slug:"d54-kubeadm-cluster", title:"Build a Multi-Node Cluster with kubeadm & Calico", yt:"Dmx36Hx-suk", mins:20,
          tags:["kubeadm","init","join","containerd","calico","swap","sysctl","br_netfilter","ip_forward","cgroup driver","token","pod-network-cidr"] },
        { id:"d55", day:55, slug:"d55-kubeadm-upgrade", title:"Upgrade a Multi-Node Cluster with kubeadm", yt:"y_PHAkH_bLU", mins:14,
          tags:["upgrade","kubeadm upgrade","drain","cordon","uncordon","version skew","kubelet","apt-mark hold"] },
        { id:"d56", day:56, slug:"d56-monitoring-logging", title:"Monitoring & Logging", yt:"EASFfeAywNw", mins:12,
          tags:["metrics-server","kubectl top","logs","journalctl","prometheus","grafana","crictl","/var/log/pods","events"] },
        { id:"d57", day:57, slug:"d57-troubleshoot-control-plane", title:"Control Plane Troubleshooting Guide", yt:"-jpnd2uiJlU", mins:15,
          tags:["troubleshooting","api server down","etcd","scheduler","controller manager","static pod manifests","certificates expired","kubeconfig"] },
        { id:"d58", day:58, slug:"d58-troubleshoot-data-plane", title:"Data Plane (Worker Node) Troubleshooting Guide", yt:"cBw0I7u2oVk", mins:15,
          tags:["node NotReady","kubelet","containerd","kube-proxy","cni","disk pressure","memory pressure","certificate","journalctl -u kubelet"] },
        { id:"d59", day:59, slug:"d59-jsonpath", title:"JSONPath with kubectl", yt:"IAZqe4QVt54", mins:11,
          tags:["jsonpath","custom-columns","-o","sort-by","range","jq","yq","output formats"] },
      ]},
    { id:"m13", num:13, title:"What's Next", color:"#16a34a",
      blurb:"Beyond CKA: GitOps with Argo CD, CI with Jenkins, and where to go from here.",
      lessons:[
        { id:"d60", day:"+", slug:"d60-whats-next", title:"Beyond CKA: Argo CD, Jenkins & the Road Ahead", yt:"Q5RvLl6KDqU", mins:7, extraYt:"bBx6UfQP1Lo",
          tags:["argo cd","gitops","jenkins","ci/cd","ckad","cks","next steps"] },
      ]},
  ],
  linux: [
    { id:"l01", slug:"l01-processes-signals", title:"Processes, PID 1 & Signals", mins:12,
      tags:["process","pid","ps","signal","SIGTERM","SIGKILL","zombie","init","exec","fork","/proc"],
      blurb:"Why containers die the way they do: PID 1, exec vs shell form, graceful shutdown." },
    { id:"l02", slug:"l02-namespaces", title:"Linux Namespaces", mins:12,
      tags:["namespace","pid","net","mnt","uts","ipc","user","unshare","nsenter","lsns"],
      blurb:"The isolation primitive: what a container actually is." },
    { id:"l03", slug:"l03-cgroups", title:"Control Groups (cgroups)", mins:11,
      tags:["cgroup","cpu.max","memory.max","oom","throttling","systemd","slice","cgroup v2"],
      blurb:"Where requests, limits, throttling and OOMKilled really come from." },
    { id:"l04", slug:"l04-filesystems-overlayfs", title:"Filesystems, Mounts & OverlayFS", mins:12,
      tags:["mount","overlayfs","union","layers","copy-on-write","bind mount","tmpfs","df","du","/proc/mounts"],
      blurb:"Image layers, writable container layers and every kind of volume are just mounts." },
    { id:"l05", slug:"l05-networking", title:"Linux Networking: veth, Bridges, Routing & iptables", mins:16,
      tags:["veth","bridge","ip route","iptables","nat","dnat","conntrack","ip netns","ss","tcpdump","ipvs","ebpf"],
      blurb:"The plumbing behind CNI, Services, kube-proxy and NetworkPolicies." },
    { id:"l06", slug:"l06-users-capabilities", title:"Users, Permissions & Capabilities", mins:11,
      tags:["uid","gid","root","chmod","chown","capabilities","CAP_NET_BIND_SERVICE","setuid","seccomp","apparmor","no_new_privs"],
      blurb:"What runAsNonRoot, capabilities and privileged really change." },
    { id:"l07", slug:"l07-systemd-journald", title:"systemd, Units & journald", mins:10,
      tags:["systemd","systemctl","unit","service","journalctl","enable","restart","drop-in","kubelet.service"],
      blurb:"kubelet and containerd are systemd services; this is how you drive and debug them." },
    { id:"l08", slug:"l08-dns-resolution", title:"DNS Resolution on Linux", mins:10,
      tags:["resolv.conf","nsswitch","hosts","dig","nslookup","search","ndots","resolver","stub"],
      blurb:"How a name becomes an IP — the mechanism CoreDNS plugs into." },
    { id:"l09", slug:"l09-openssl-certificates", title:"Certificates with OpenSSL", mins:12,
      tags:["openssl","x509","csr","key","pem","crt","san","verify","expiry","chain","base64"],
      blurb:"Read, create and verify every certificate in /etc/kubernetes/pki." },
    { id:"l10", slug:"l10-shell-toolkit", title:"The Troubleshooter's Shell Toolkit", mins:12,
      tags:["grep","awk","sed","jq","yq","curl","ss","lsof","strace","watch","xargs","tee","find","df","free","top"],
      blurb:"The commands you reach for during an outage (and in the exam)." },
  ],
  /* CI/CD & GitOps track — pipelines that put changes into the cluster.
     Reference links per lesson go in `refs: [{t:"title", u:"url"}]` (shown as chips). */
  cicd: [
    { id:"c01", refs:[{t:"GitHub Actions: Beginner to PRO (video)", u:"https://www.youtube.com/watch?v=U0S7ddSGaYI"},{t:"Jenkins DevOps Masterclass (video, from 2:41:06)", u:"https://www.youtube.com/watch?v=wj8ELsJ-S5Q&t=9666s"},{t:"Argo CD: Complete GitOps Course (video, from 24:12)", u:"https://www.youtube.com/watch?v=m4lDTQwK1T8&t=1452s"}], slug:"c01-cicd-fundamentals", title:"CI/CD Fundamentals: From Commit to Cluster", mins:12,
      tags:["ci","cd","pipeline","continuous integration","continuous delivery","continuous deployment","artifact","image tag","sha","registry","environments","promotion","push vs pull"],
      blurb:"What a pipeline is, why the image is the artifact, immutable tags, environments, and push vs pull deploys." },
    { id:"c02", yt:"U0S7ddSGaYI", ytBy:"Cloud With VarJosh · Complete GitHub Actions Tutorial: Beginner to PRO", refs:[{t:"GitHub Actions: Beginner to PRO (video)", u:"https://www.youtube.com/watch?v=U0S7ddSGaYI"}], slug:"c02-github-actions", title:"GitHub Actions: Workflows, Jobs, Steps & Runners", mins:16,
      tags:["github actions","workflow","on","jobs","steps","runs-on","runner","self-hosted","uses","run","matrix","cache","artifacts","secrets","GITHUB_TOKEN","permissions","contexts","expressions","reusable workflow","composite action"],
      blurb:"The anatomy of a workflow, what a runner actually is, contexts, secrets, matrices, caching and reuse." },
    { id:"c03", yt:"U0S7ddSGaYI", ytBy:"Cloud With VarJosh · Complete GitHub Actions Tutorial: Beginner to PRO", refs:[{t:"GitHub Actions: Beginner to PRO (video)", u:"https://www.youtube.com/watch?v=U0S7ddSGaYI"}], slug:"c03-github-actions-kubernetes", title:"GitHub Actions → Kubernetes: Build, Push, Deploy & OIDC", mins:15,
      tags:["build-push-action","buildx","ghcr","docker login","kubeconfig secret","kubectl set image","helm upgrade","oidc","aws-actions","assume role","eks","environments","approvals","rollout status","actions-runner-controller","arc"],
      blurb:"Build and push images, deploy with kubectl/Helm, swap long-lived secrets for OIDC, and run runners in the cluster." },
    { id:"c04", yt:"wj8ELsJ-S5Q", ytBy:"Cloud With VarJosh · How CI/CD Works in Production | Jenkins-Based DevOps Masterclass", refs:[{t:"Jenkins DevOps Masterclass (video, from 2:41:06)", u:"https://www.youtube.com/watch?v=wj8ELsJ-S5Q&t=9666s"}], slug:"c04-jenkins", title:"Jenkins: Controller, Agents & Declarative Pipelines", mins:15,
      tags:["jenkins","controller","agent","executor","jenkinsfile","declarative pipeline","scripted","stages","steps","post","parallel","input","withCredentials","credentials","plugins","multibranch","webhook","shared library","JENKINS_HOME"],
      blurb:"How Jenkins is put together, how a Jenkinsfile runs, credentials, plugins, multibranch and shared libraries." },
    { id:"c05", yt:"wj8ELsJ-S5Q", ytBy:"Cloud With VarJosh · How CI/CD Works in Production | Jenkins-Based DevOps Masterclass", refs:[{t:"Jenkins DevOps Masterclass (video, from 2:41:06)", u:"https://www.youtube.com/watch?v=wj8ELsJ-S5Q&t=9666s"}], slug:"c05-jenkins-on-kubernetes", title:"Jenkins on Kubernetes: Dynamic Pod Agents & Kaniko", mins:13,
      tags:["jenkins kubernetes plugin","pod template","jnlp","inbound agent","container()","kaniko","buildah","docker socket","dind","helm jenkins","jcasc","statefulset","pvc","rbac"],
      blurb:"One Pod per build: how the Kubernetes plugin schedules agents and how to build images without a Docker daemon." },
    { id:"c06", refs:[{t:"Argo CD: Complete GitOps Course (video, from 24:12)", u:"https://www.youtube.com/watch?v=m4lDTQwK1T8&t=1452s"}], slug:"c06-gitops-principles", title:"GitOps: Principles, Push vs Pull & Reconciliation", mins:12,
      tags:["gitops","opengitops","declarative","versioned","pulled","reconciled","drift","self-heal","push vs pull","config repo","app repo","environments","promotion","flux","argo cd"],
      blurb:"Git as the desired state and a controller that makes the cluster match it — the same loop as every controller in the course." },
    { id:"c07", yt:"m4lDTQwK1T8", ytBy:"Cloud With VarJosh · How Argo CD Works in Production | Complete GitOps Course", refs:[{t:"Argo CD: Complete GitOps Course (video, from 24:12)", u:"https://www.youtube.com/watch?v=m4lDTQwK1T8&t=1452s"}], slug:"c07-argocd-architecture", title:"Argo CD: Architecture, Install & the Application CRD", mins:15,
      tags:["argo cd","argocd","argocd-server","repo-server","application-controller","redis","dex","install","argocd login","application","source","destination","targetRevision","syncPolicy","appproject","project","rbac","sso","tracking"],
      blurb:"The components, how to install and log in, and every field of the Application resource that matters." },
    { id:"c08", yt:"m4lDTQwK1T8", ytBy:"Cloud With VarJosh · How Argo CD Works in Production | Complete GitOps Course", refs:[{t:"Argo CD: Complete GitOps Course (video, from 24:12)", u:"https://www.youtube.com/watch?v=m4lDTQwK1T8&t=1452s"}], slug:"c08-argocd-sync", title:"Argo CD Sync: Status, Health, Hooks, Waves, Diff & Rollback", mins:14,
      tags:["sync","outofsync","synced","health","healthy","degraded","progressing","hooks","presync","postsync","sync wave","sync options","prune","selfHeal","ignoreDifferences","diff","rollback","history","ComparisonError"],
      blurb:"What Synced and Healthy really mean, ordering a sync with hooks and waves, taming diffs, and rolling back." },
    { id:"c09", yt:"m4lDTQwK1T8", ytBy:"Cloud With VarJosh · How Argo CD Works in Production | Complete GitOps Course", refs:[{t:"Argo CD: Complete GitOps Course (video, from 24:12)", u:"https://www.youtube.com/watch?v=m4lDTQwK1T8&t=1452s"}], slug:"c09-argocd-scale", title:"Argo CD at Scale: Helm & Kustomize Sources, App of Apps, ApplicationSets & Multi-Cluster", mins:14,
      tags:["helm source","kustomize source","multi-source","app of apps","applicationset","generators","list generator","cluster generator","git generator","matrix","multi-cluster","argocd cluster add","image updater","argo rollouts","canary","blue-green","notifications"],
      blurb:"Rendering Helm and Kustomize, bootstrapping with App of Apps, stamping out Applications with generators, many clusters." },
    { id:"c10", refs:[{t:"GitHub Actions: Beginner to PRO (video)", u:"https://www.youtube.com/watch?v=U0S7ddSGaYI"},{t:"Jenkins DevOps Masterclass (video, from 2:41:06)", u:"https://www.youtube.com/watch?v=wj8ELsJ-S5Q&t=9666s"},{t:"Argo CD: Complete GitOps Course (video, from 24:12)", u:"https://www.youtube.com/watch?v=m4lDTQwK1T8&t=1452s"}], slug:"c10-end-to-end-pipeline", title:"End-to-End: From Pull Request to Production", mins:14,
      tags:["end to end","reference architecture","app repo","config repo","promotion","pull request","trivy","cosign","signing","sbom","admission policy","rollback playbook","hotfix","notifications","dev staging prod"],
      blurb:"The whole chain wired together — GitHub Actions or Jenkins → registry → config repo → Argo CD → rollout — with the security and rollback story." },
  ],
  extras: [
    { id:"cheatsheet", slug:"cheatsheet", title:"kubectl Cheatsheet", tags:["kubectl","cheatsheet","commands","reference"] },
    { id:"glossary", slug:"glossary", title:"Glossary", tags:["glossary","terms","definitions"] },
  ]
};
